In [31]:
import pandas as pd
import numpy as np
pd.set_option('max_colwidth', 400)

In [32]:
movies_df = pd.read_csv('csvs/train.csv')
movies_df.head()

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,release_date,runtime,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue
0,1,"[{'id': 313576, 'name': 'Hot Tub Time Machine Collection', 'poster_path': '/iEhb00TGPucF0b4joM1ieyY026U.jpg', 'backdrop_path': '/noeTVcgpBiD48fDjFVic1Vz7ope.jpg'}]",14000000,"[{'id': 35, 'name': 'Comedy'}]",NaN,tt2637294,en,Hot Tub Time Machine 2,"When Lou, who has become the ""father of the Internet,"" is shot by an unknown assailant, Jacob and Nick fire up the time machine again to save their friend.",6.575393,...,2/20/15,93.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The Laws of Space and Time are About to be Violated.,Hot Tub Time Machine 2,"[{'id': 4379, 'name': 'time travel'}, {'id': 9663, 'name': 'sequel'}, {'id': 11830, 'name': 'hot tub'}, {'id': 179431, 'name': 'duringcreditsstinger'}]","[{'cast_id': 4, 'character': 'Lou', 'credit_id': '52fe4ee7c3a36847f82afae7', 'gender': 2, 'id': 52997, 'name': 'Rob Corddry', 'order': 0, 'profile_path': '/k2zJL0V1nEZuFT08xUdOd3ucfXz.jpg'}, {'cast_id': 5, 'character': 'Nick', 'credit_id': '52fe4ee7c3a36847f82afaeb', 'gender': 2, 'id': 64342, 'name': 'Craig Robinson', 'order': 1, 'profile_path': '/tVaRMkJXOEVhYxtnnFuhqW0Rjzz.jpg'}, {'cast_id':...","[{'credit_id': '59ac067c92514107af02c8c8', 'department': 'Directing', 'gender': 0, 'id': 1449071, 'job': 'First Assistant Director', 'name': 'Kelly Cantley', 'profile_path': None}, {'credit_id': '52fe4ee7c3a36847f82afad7', 'department': 'Directing', 'gender': 2, 'id': 3227, 'job': 'Director', 'name': 'Steve Pink', 'profile_path': '/myHOgo8mQSCiCAZNGMRdHVr03jr.jpg'}, {'credit_id': '5524ed25c3a3...",12314651
1,2,"[{'id': 107674, 'name': 'The Princess Diaries Collection', 'poster_path': '/wt5AMbxPTS4Kfjx7Fgm149qPfZl.jpg', 'backdrop_path': '/zSEtYD77pKRJlUPx34BJgUG9v1c.jpg'}]",40000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'name': 'Drama'}, {'id': 10751, 'name': 'Family'}, {'id': 10749, 'name': 'Romance'}]",NaN,tt0368933,en,The Princess Diaries 2: Royal Engagement,"Mia Thermopolis is now a college graduate and on her way to Genovia to take up her duties as princess. Her best friend Lilly also joins her for the summer. Mia continues her 'princess lessons'- riding horses side-saddle, archery, and other royal. But her complicated life is turned upside down once again when she not only learns that she is to take the crown as queen earlier than expected...",8.248895,...,8/6/04,113.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,It can take a lifetime to find true love; she's got 30 days!,The Princess Diaries 2: Royal Engagement,"[{'id': 2505, 'name': 'coronation'}, {'id': 4263, 'name': 'duty'}, {'id': 6038, 'name': 'marriage'}, {'id': 13072, 'name': 'falling in love'}]","[{'cast_id': 1, 'character': 'Mia Thermopolis', 'credit_id': '52fe43fe9251416c7502561f', 'gender': 1, 'id': 1813, 'name': 'Anne Hathaway', 'order': 0, 'profile_path': '/jUMOKwSUBnTcMeN1HfhutiY49Ad.jpg'}, {'cast_id': 2, 'character': 'Queen Clarisse Renaldi', 'credit_id': '52fe43fe9251416c75025623', 'gender': 1, 'id': 5823, 'name': 'Julie Andrews', 'order': 1, 'profile_path': '/6t61jkmfSA6nbYRCK...","[{'credit_id': '52fe43fe9251416c7502563d', 'department': 'Directing', 'gender': 2, 'id': 1201, 'job': 'Director', 'name': 'Garry Marshall', 'profile_path': '/kx77E8p5rnEmKxIhFT0qWCEMEik.jpg'}, {'credit_id': '52fe43fe9251416c75025667', 'department': 'Camera', 'gender': 2, 'id': 1214, 'job': 'Director of Photography', 'name': 'Charles Minsky', 'profile_path': None}, {'credit_id': '52fe43fe925141...",95149435
2,3,NaN,3300000,"[{'id': 18, 'name': 'Drama'}]",http://sonyclassics.com/whiplash/,tt2582802,en,Whiplash,"Under the direction of a ruthless instructor, a talented young drummer begins to pursue perfection at any cost, even his humanity.",64.299990,...,10/10/14,105.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The road to greatness can take you to the edge.,Whiplash,"[{'id': 1416, 'name': 'jazz'}, {'id': 1523, 'name': 'obsession'}, {'id': 1640, 'name': 'conservatory'}, {'id': 2176, 'name': 'music teacher'}, {'id': 14512, 'name': 'new york city'}, {'id': 14819, 'name': 'violence'}, {'id': 33896, 'name': 'montage'}, {'id': 156823, 'name': 'drummer'}, {'id': 170418, 'name': 'public humiliation'}, {'id': 176095, 'name': 'jazz band'}, {'id': 206298, 'name': 'yo...","[{'cast_id': 5, 'character': 'Andrew Neimann', 'credit_id': '52fe4ef7c3a36847f82b3fc3', 'gender': 2, 'id': 996701, 'name': 'Miles Teller', 'order': 0, 'profile_path': '/o2wfvYAvspsKqYVt4ORR8VWjB7H.jpg'}, {'cast_id': 6, 'character': 'Terence Fletcher', 'credit_id': '52fe4ef7c3a36847f82b3fc7', 'gender': 2, 'id': 18999, 'name': 'J.K. Simmons', 'order': 1, 'profile_path': '/jPoNW5fugs5h8AbcE7H5OBm...","[{'credit_id': '54d5356ec3a3683ba0000039', 'department': 'Production', 'gender': 1, 'id': 494, 'job': 'Casting', 'name': 'Terri Taylor', 'profile_path': None}, {'credit_id': '56407fa89251417055000b58', 'department': 'Sound', 'gender': 0, 'id': 6745, 'job': 'Music Editor', 'name': 'Richard Henderson', 'profile_path': None}, {'credit_id': '5789212392514135d60025fd', 'department': 'Production', '...",13092000
3,4,NaN,1200000,"[{'id': 53, 'name': 'Thriller'}, {'id': 18, 'name': 'Drama'}]",http://kahaanithefilm.com/,tt1821480,hi,Kahaani,"Vidya Bagchi (Vidya Balan) arrives in Kolkata from London to find her missing husband Arnab Bagchi. Seven months pregnant and alone in a festive city, she begins a relentless search for her husband. With nothing to rely on except fragments from her memories about him, all clues seem to reach a dead end when everyone tries to convince Vidya that her husband does not exist. She slowly realises t...",3.174936,...,3/9/12,122.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso_639_1': 'hi', 'name': 'हिन्दी'}]",Released,NaN,Kahaani,"[{'id': 10092, 'name': 'mystery'}, {'id': 10540, 'name': 'bollywood'}, {'id': 11734, 'name': 'police corruption'}, {'id': 14536, 'name': 'crime'}, {'id': 14636, 'name': 'india'}, {'id': 208364, 'name': 'missing husband'}, {'id': 220935, 'name': 'nerve gas'}]","[{'cast_id': 1, 'character': 'Vidya Bagchi', 'credit_id': '52fe48779251416c9108d6d9', 'gender': 1, 'id': 35068, 'name': 'Vidya Balan', 'order': 0, 'profile_path': '/anMmmqKY11jcm0UnSSakfNOSCyB.jpg'}, {'cast_id': 5, 'character': '', 'credit_id': '57722abec3a368245b004519', 'gender': 2, 'id': 85047, 'name': 'Nawazuddin Siddiqui', 'order': 1, 'profile_path': '/2Kv2ENAs1ETAFTQ6mC1jbDzEzIN.jpg'}, {...","[{'credit_id': '52fe48779251416c9108d6eb', 'department': 'Directing', 'gender': 0, 'id': 95510, 'job': 'Director', 'name': 'Sujoy Ghosh', 'profile_path': None}, {'credit_id': '52fe48779251416c9108d6e5', 'department': 'Production', 'gender': 0, 'id': 95510, 'job': 'Producer', 'name': 'Sujoy Ghosh', 'profile_path': None}, {'credit_id': '52fe48779251416c9108d6df', 'department': 'Writing', 'gender...",16000000
4,5,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'name': 'Thriller'}]",NaN,tt1380152,ko,마린보이,"Marine Boy is the story of a former national swimmer who finds himself in debt, and out of desperation is employed as a mule by a gangster boss, smuggling drugs by sea.",1.148070,...,2/5/09,118.0,"[{'iso_639_1': 'ko', 'name': '한국어/조선말'}]",Released,NaN,Marine Boy,NaN,"[{'cast_id': 3, 'character': 'Chun-soo', 'credit_id': '52fe464b9251416c75073b47', 'gender': 2, 'id': 84751, 'name': 'Kim Kang-woo', 'order': 0, 'profile_path': '/lJvcgUx1qEnNfGcCtbmp3EC5vCG.jpg'}, {'cast_id': 4, 'character': 'Company president Kang', 'credit_id': '52fe464b9251416c75073b4b', 'gender': 2, 'id': 64453, 'name': 'Jo Jae-hyeon', 'order': 1, 'profile_path': '/2QVUP8t3zmKcwlm7IBOzPVik...","[{'credit_id': '52fe464b9251416c75073b43', 'department': 'Directing', 'gender': 0, 'id': 84749, 'job': 'Director', 'name': 'Jong-seok Yoon', 'profile_path': None}, {'credit_id': '52fe464b9251416c75073b55', 'department': 'Writing', 'gender': 0, 'id': 84749, 'job': 'Writer', 'name': 'Jong-seok Yoon', 'profile_path': None}]",3923970

In [33]:
movies_df.columns

Index(['id', 'belongs_to_collection', 'budget', 'genres', 'homepage',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'runtime', 'spoken_languages',
       'status', 'tagline', 'title', 'Keywords', 'cast', 'crew', 'revenue'],
      dtype='object')

In [34]:
movies_df_clean = movies_df.drop(['homepage', 'imdb_id', 'original_language', 
                                  'overview', 'poster_path', 'production_countries', 'status',
                                 'crew', 'tagline', 'belongs_to_collection'], axis=1)
movies_df_clean.head()

,id,budget,genres,original_title,popularity,production_companies,release_date,runtime,spoken_languages,title,Keywords,cast,revenue
0,1,14000000,"[{'id': 35, 'name': 'Comedy'}]",Hot Tub Time Machine 2,6.575393,"[{'name': 'Paramount Pictures', 'id': 4}, {'name': 'United Artists', 'id': 60}, {'name': 'Metro-Goldwyn-Mayer (MGM)', 'id': 8411}]",2/20/15,93.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Hot Tub Time Machine 2,"[{'id': 4379, 'name': 'time travel'}, {'id': 9663, 'name': 'sequel'}, {'id': 11830, 'name': 'hot tub'}, {'id': 179431, 'name': 'duringcreditsstinger'}]","[{'cast_id': 4, 'character': 'Lou', 'credit_id': '52fe4ee7c3a36847f82afae7', 'gender': 2, 'id': 52997, 'name': 'Rob Corddry', 'order': 0, 'profile_path': '/k2zJL0V1nEZuFT08xUdOd3ucfXz.jpg'}, {'cast_id': 5, 'character': 'Nick', 'credit_id': '52fe4ee7c3a36847f82afaeb', 'gender': 2, 'id': 64342, 'name': 'Craig Robinson', 'order': 1, 'profile_path': '/tVaRMkJXOEVhYxtnnFuhqW0Rjzz.jpg'}, {'cast_id':...",12314651
1,2,40000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'name': 'Drama'}, {'id': 10751, 'name': 'Family'}, {'id': 10749, 'name': 'Romance'}]",The Princess Diaries 2: Royal Engagement,8.248895,"[{'name': 'Walt Disney Pictures', 'id': 2}]",8/6/04,113.0,"[{'iso_639_1': 'en', 'name': 'English'}]",The Princess Diaries 2: Royal Engagement,"[{'id': 2505, 'name': 'coronation'}, {'id': 4263, 'name': 'duty'}, {'id': 6038, 'name': 'marriage'}, {'id': 13072, 'name': 'falling in love'}]","[{'cast_id': 1, 'character': 'Mia Thermopolis', 'credit_id': '52fe43fe9251416c7502561f', 'gender': 1, 'id': 1813, 'name': 'Anne Hathaway', 'order': 0, 'profile_path': '/jUMOKwSUBnTcMeN1HfhutiY49Ad.jpg'}, {'cast_id': 2, 'character': 'Queen Clarisse Renaldi', 'credit_id': '52fe43fe9251416c75025623', 'gender': 1, 'id': 5823, 'name': 'Julie Andrews', 'order': 1, 'profile_path': '/6t61jkmfSA6nbYRCK...",95149435
2,3,3300000,"[{'id': 18, 'name': 'Drama'}]",Whiplash,64.299990,"[{'name': 'Bold Films', 'id': 2266}, {'name': 'Blumhouse Productions', 'id': 3172}, {'name': 'Right of Way Films', 'id': 32157}]",10/10/14,105.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Whiplash,"[{'id': 1416, 'name': 'jazz'}, {'id': 1523, 'name': 'obsession'}, {'id': 1640, 'name': 'conservatory'}, {'id': 2176, 'name': 'music teacher'}, {'id': 14512, 'name': 'new york city'}, {'id': 14819, 'name': 'violence'}, {'id': 33896, 'name': 'montage'}, {'id': 156823, 'name': 'drummer'}, {'id': 170418, 'name': 'public humiliation'}, {'id': 176095, 'name': 'jazz band'}, {'id': 206298, 'name': 'yo...","[{'cast_id': 5, 'character': 'Andrew Neimann', 'credit_id': '52fe4ef7c3a36847f82b3fc3', 'gender': 2, 'id': 996701, 'name': 'Miles Teller', 'order': 0, 'profile_path': '/o2wfvYAvspsKqYVt4ORR8VWjB7H.jpg'}, {'cast_id': 6, 'character': 'Terence Fletcher', 'credit_id': '52fe4ef7c3a36847f82b3fc7', 'gender': 2, 'id': 18999, 'name': 'J.K. Simmons', 'order': 1, 'profile_path': '/jPoNW5fugs5h8AbcE7H5OBm...",13092000
3,4,1200000,"[{'id': 53, 'name': 'Thriller'}, {'id': 18, 'name': 'Drama'}]",Kahaani,3.174936,NaN,3/9/12,122.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso_639_1': 'hi', 'name': 'हिन्दी'}]",Kahaani,"[{'id': 10092, 'name': 'mystery'}, {'id': 10540, 'name': 'bollywood'}, {'id': 11734, 'name': 'police corruption'}, {'id': 14536, 'name': 'crime'}, {'id': 14636, 'name': 'india'}, {'id': 208364, 'name': 'missing husband'}, {'id': 220935, 'name': 'nerve gas'}]","[{'cast_id': 1, 'character': 'Vidya Bagchi', 'credit_id': '52fe48779251416c9108d6d9', 'gender': 1, 'id': 35068, 'name': 'Vidya Balan', 'order': 0, 'profile_path': '/anMmmqKY11jcm0UnSSakfNOSCyB.jpg'}, {'cast_id': 5, 'character': '', 'credit_id': '57722abec3a368245b004519', 'gender': 2, 'id': 85047, 'name': 'Nawazuddin Siddiqui', 'order': 1, 'profile_path': '/2Kv2ENAs1ETAFTQ6mC1jbDzEzIN.jpg'}, {...",16000000
4,5,0,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'name': 'Thriller'}]",마린보이,1.148070,NaN,2/5/09,118.0,"[{'iso_639_1': 'ko', 'name': '한국어/조선말'}]",Marine Boy,NaN,"[{'cast_id': 3, 'character': 'Chun-soo', 'credit_id': '52fe464b9251416c75073b47', 'gender': 2, 'id': 84751, 'name': 'Kim Kang-woo', 'order': 0, 'profile_path': '/lJvcgUx1qEnNfGcCtbmp3EC5vCG.jpg'}, {'cast_id': 4, 'character': 'Company president Kang', 'credit_id': '52fe464b9251416c75073b4b', 'gender': 2, 'id': 64453, 'name': 'Jo Jae-hyeon', 'order': 1, 'profile_path': '/2QVUP8t3zmKcwlm7IBOzPVik...",3923970

In [35]:
movies_df_2 = pd.read_csv('csvs/test.csv')
movies_df_2.head()

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,production_countries,release_date,runtime,spoken_languages,status,tagline,title,Keywords,cast,crew
0,3001,"[{'id': 34055, 'name': 'Pokémon Collection', 'poster_path': '/j5te0YNZAMXDBnsqTUDKIBEt8iu.jpg', 'backdrop_path': '/iGoYKA0TFfgSoZpG2u5viTJMGfK.jpg'}]",0,"[{'id': 12, 'name': 'Adventure'}, {'id': 16, 'name': 'Animation'}, {'id': 10751, 'name': 'Family'}, {'id': 14, 'name': 'Fantasy'}]",http://www.pokemon.com/us/movies/movie-pokemon-the-rise-of-darkrai-2008/,tt1226251,ja,ディアルガVSパルキアVSダークライ,"Ash and friends (this time accompanied by newcomer Dawn) arrive at an idyllic village on their way to their next Pokemon contest, where chaos will soon erupt with the prophecy of two Pokemon Gods (Dialga and Palkia) and the arrival of a mysterious, seemingly deadly Pokemon named Darkrai, which has the power to distort space and time.",3.851534,...,"[{'iso_3166_1': 'JP', 'name': 'Japan'}, {'iso_3166_1': 'US', 'name': 'United States of America'}]",7/14/07,90.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso_639_1': 'ja', 'name': '日本語'}]",Released,Somewhere Between Time & Space... A Legend Is Born.,Pokémon: The Rise of Darkrai,"[{'id': 11451, 'name': 'pok√©mon'}, {'id': 11551, 'name': 'pocket monsters'}]","[{'cast_id': 3, 'character': 'Tonio', 'credit_id': '52fe44e7c3a368484e03d68d', 'gender': 0, 'id': 82140, 'name': 'Craig Blair', 'order': 0, 'profile_path': None}, {'cast_id': 4, 'character': 'Alice', 'credit_id': '52fe44e7c3a368484e03d691', 'gender': 1, 'id': 111768, 'name': 'Emily Bauer', 'order': 1, 'profile_path': None}, {'cast_id': 5, 'character': 'Ash Ketchum', 'credit_id': '52fe44e7c3a36...","[{'credit_id': '52fe44e7c3a368484e03d683', 'department': 'Directing', 'gender': 0, 'id': 65429, 'job': 'Director', 'name': 'Kunihiko Yuyama', 'profile_path': '/9z3LqqCMRZWyptfIZnlAdG7CnaZ.jpg'}, {'credit_id': '52fe44e7c3a368484e03d689', 'department': 'Writing', 'gender': 2, 'id': 25761, 'job': 'Writer', 'name': 'Hideki Sonoda', 'profile_path': None}]"
1,3002,NaN,88000,"[{'id': 27, 'name': 'Horror'}, {'id': 878, 'name': 'Science Fiction'}]",NaN,tt0051380,en,Attack of the 50 Foot Woman,"When an abused wife grows to giant size because of an alien encounter and an aborted murder attempt, she goes after her cheating husband with revenge on her mind.",3.559789,...,"[{'iso_3166_1': 'US', 'name': 'United States of America'}]",5/19/58,65.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,A titanic beauty spreads a macabre wave of horror! A terrifying masterpiece of shock and chills!,Attack of the 50 Foot Woman,"[{'id': 9748, 'name': 'revenge'}, {'id': 9951, 'name': 'alien'}, {'id': 11034, 'name': 'b movie'}, {'id': 11513, 'name': 'cheating husband'}, {'id': 14819, 'name': 'violence'}, {'id': 15184, 'name': 'woman'}, {'id': 189099, 'name': 'giant'}, {'id': 208199, 'name': 'chrysler imperial'}]","[{'cast_id': 2, 'character': 'Nancy Fowler Archer', 'credit_id': '52fe47949251416c7509e999', 'gender': 1, 'id': 104412, 'name': 'Allison Hayes', 'order': 0, 'profile_path': '/6VoMLGGRH1ccl25cyaHJWyMapD0.jpg'}, {'cast_id': 3, 'character': 'Harry Archer', 'credit_id': '52fe47949251416c7509e99d', 'gender': 0, 'id': 108299, 'name': 'William Hudson', 'order': 1, 'profile_path': '/yJDm8q5pzge2HfDeN9...","[{'credit_id': '55807805c3a3685b1300060b', 'department': 'Editing', 'gender': 2, 'id': 13781, 'job': 'Editor', 'name': 'Edward Mann', 'profile_path': None}, {'credit_id': '558077f392514127100007bb', 'department': 'Camera', 'gender': 2, 'id': 40392, 'job': 'Director of Photography', 'name': 'Jacques R. Marquette', 'profile_path': None}, {'credit_id': '558077c6c3a3685c8b000429', 'department': 'P..."
2,3003,NaN,0,"[{'id': 35, 'name': 'Comedy'}, {'id': 10749, 'name': 'Romance'}]",NaN,tt0118556,en,Addicted to Love,"Good-natured astronomer Sam is devastated when the love of his life, Linda, leaves him for a suave Frenchman named Anton. He therefore does what every other normal dumpee would do; go to New York and set up home in the abandoned building opposite his ex-girlfriend's apartment, intent on winning her back and waiting until she decides to leave her current lover.",8.085194,...,"[{'iso_3166_1': 'US', 'name': 'United States of America'}]",5/23/97,100.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,A Comedy About Lost Loves And Last Laughs,Addicted to Love,"[{'id': 931, 'name': 'jealousy'}, {'id': 9673, 'name': 'love'}, {'id': 9748, 'name': 'revenge'}, {'id': 14602, 'name': 'break-up'}]","[{'cast_id': 11, 'character': 'Maggie', 'credit_id': '52fe4330c3a36847f804139b', 'gender': 1, 'id': 5344, 'name': 'Meg Ryan', 'order': 0, 'profile_path': '/iv33eEcSakPCkO2MiR4bIZpjgyg.jpg'}, {'cast_id': 12, 'character': 'Sam', 'credit_id': '52fe4330c3a36847f804139f', 'gender': 2, 'id': 4756, 'name': 'Matthew Broderick', 'order': 1, 'profile_path': '/j9ETatVKFxYR5Ijk8l5tzKO4HPn.jpg'}, {'cast_id...","[{'credit_id': '52fe4330c3a36847f8041367', 'department': 'Directing', 'gender': 0, 'id': 2171, 'job': 'Director', 'name': 'Griffin Dunne', 'profile_path': '/4oCLupH3Uo2otzF77LrYE4s1iqw.jpg'}, {'credit_id': '52fe4330c3a36847f804136d', 'department': 'Production', 'gender': 0, 'id': 21146, 'job': 'Producer', 'name': 'Robert F. Newmyer', 'profile_path': None}, {'credit_id': '52fe4330c3a36847f80413..."
3,3004,NaN,6800000,"[{'id': 18, 'name': 'Drama'}, {'id': 10752, 'name': 'War'}, {'id': 9648, 'name': 'Mystery'}]",http://www.sonyclassics.com/incendies/,tt1255953,fr,Incendies,"A mother's last wishes send twins Jeanne and Simon on a journey to Middle East in search of their tangled roots. Adapted from Wajdi Mouawad's acclaimed play, Incendies tells the powerful and moving tale of two young adults' voyage to the core of deep-rooted hatred, never-ending wars and enduring love.",8.596012,...,"[{'iso_3166_1': 'CA', 'name': 'Canada'}, {'iso_3166_1': 'FR', 'name': 'France'}]",9/4/10,130.0,"[{'iso_639_1': 'fr', 'name': 'Français'}, {'iso_639_1': 'ar', 'name': 'العربية'}, {'iso_639_1': 'en', 'name': 'English'}]",Released,The search began at the opening of their mother's will.,Incendies,"[{'id': 378, 'name': 'prison'}, {'id': 539, 'name': 'middle east'}, {'id': 570, 'name': 'rape'}, {'id': 789, 'name': 'muslim'}, {'id': 1550, 'name': 'militia'}, {'id': 2297, 'name': 'interpreter'}, {'id': 5153, 'name': 'son'}, {'id': 5950, 'name': 'christian'}, {'id': 6783, 'name': 'orphanage'}, {'id': 8181, 'name': 'swimming pool'}, {'id': 14546, 'name': 'massacre'}, {'id': 14547, 'name': 'ch...","[{'cast_id': 6, 'character': 'Nawal', 'credit_id': '52fe470ac3a36847f812058b', 'gender': 1, 'id': 77498, 'name': 'Lubna Azabal', 'order': 0, 'profile_path': '/lGvB2xP7sotwSslSTovL5nxnzBC.jpg'}, {'cast_id': 7, 'character': 'Jeanne Marwan', 'credit_id': '52fe470ac3a36847f812058f', 'gender': 1, 'id': 84573, 'name': 'M√©lissa D√©sormeaux-Poulin', 'order': 1, 'profile_path': '/aBiUPDJwHwdcGPfEpi8kl...","[{'credit_id': '56478092c3a36826140043af', 'department': 'Visual Effects', 'gender': 2, 'id': 4657, 'job': 'Special Effects Supervisor', 'name': 'Louis Craig', 'profile_path': None}, {'credit_id': '5648ca1bc3a368262000840e', 'department': 'Production', 'gender': 0, 'id': 6997, 'job': 'Casting', 'name': 'Lucie Robitaille', 'profile_path': None}, {'credit_id': '564777ce9251413ae1003db6', 'depart..."
4,3005,NaN,2000000,"[{'id': 36, 'name': 'History'}, {'id': 99, 'name': 'Documentary'}]",NaN,tt0418753,en,Inside Deep Throat,"In 1972, a seemingly typical shoestring budget pornographic film was made in a Florida hotel, ""Deep Throat,"" starring Linda Lovelace. This film would surpass the wildest expectation of everyone involved to become one of the most successful independent films of all time. It caught the public imagination which met the spirit of the times, even as the self appointed guardians of public morality s...",3.217680,...,"[{'iso_3166_1': 'US', 'name': 'United States of America'}]",2/11/05,92.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,It was filmed in 6 days for 25 thousand dollars. The government didn't want you to see it. It was banned in 23 states. It has grossed over 600 million dollars. And it is the most profitable film in motion picture history.,Inside Deep Throat,"[{'id': 279, 'name': 'usa'}, {'id': 1228, 'name': '1970s'}, {'id': 5436, 'name': 'sexual revolution'}, {'id': 12420, 'name': 'unsimulated sex'}]","[{'cast_id': 1, 'character': 'Narrator (voice)', 'credit_id': '52fe44ce9251416c75041931', 'gender': 2, 'id': 2778, 'name': 'Dennis Hopper', 'order': 0, 'profile_path': '/56nj2DfMVU3F9qUagZWMePLbrKF.jpg'}, {'cast_id': 2, 'character': 'Himself', 'credit_id': '52fe44ce9251416c75041935', 'gender': 2, 'id': 71766, 'name': 'Peter Bart', 'order': 1, 'profile_path': '/iSDH6UtPjjKjJwzJWkbXhlljxAr.jpg'}...","[{'credit_id': '52fe44ce9251416c75041967', 'department': 'Production', 'gender': 2, 'id': 339, 'job': 'Producer', 'name': 'Brian Grazer', 'profile_path': '/yqiKX3auDuorea0BOtuB6Ifhyp6.jpg'}, {'credit_id': '52fe44ce9251416c7504196d', 'department': 'Production', 'gender': 1, 'id': 5284, 'job': 'Executive Producer', 'name': 'Kim Roth', 'profile_path': None}, {'credit_id': '52fe44ce9251416c7504197..."

In [36]:
movies_df_2.columns

Index(['id', 'belongs_to_collection', 'budget', 'genres', 'homepage',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'runtime', 'spoken_languages',
       'status', 'tagline', 'title', 'Keywords', 'cast', 'crew'],
      dtype='object')

In [37]:
movies_df_2_clean = movies_df_2.drop(['homepage', 'imdb_id', 'original_language', 
                                  'overview', 'poster_path', 'production_countries', 'status',
                                 'crew', 'tagline', 'belongs_to_collection'], axis=1)
movies_df_2_clean.head()

,id,budget,genres,original_title,popularity,production_companies,release_date,runtime,spoken_languages,title,Keywords,cast
0,3001,0,"[{'id': 12, 'name': 'Adventure'}, {'id': 16, 'name': 'Animation'}, {'id': 10751, 'name': 'Family'}, {'id': 14, 'name': 'Fantasy'}]",ディアルガVSパルキアVSダークライ,3.851534,NaN,7/14/07,90.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso_639_1': 'ja', 'name': '日本語'}]",Pokémon: The Rise of Darkrai,"[{'id': 11451, 'name': 'pok√©mon'}, {'id': 11551, 'name': 'pocket monsters'}]","[{'cast_id': 3, 'character': 'Tonio', 'credit_id': '52fe44e7c3a368484e03d68d', 'gender': 0, 'id': 82140, 'name': 'Craig Blair', 'order': 0, 'profile_path': None}, {'cast_id': 4, 'character': 'Alice', 'credit_id': '52fe44e7c3a368484e03d691', 'gender': 1, 'id': 111768, 'name': 'Emily Bauer', 'order': 1, 'profile_path': None}, {'cast_id': 5, 'character': 'Ash Ketchum', 'credit_id': '52fe44e7c3a36..."
1,3002,88000,"[{'id': 27, 'name': 'Horror'}, {'id': 878, 'name': 'Science Fiction'}]",Attack of the 50 Foot Woman,3.559789,"[{'name': 'Woolner Brothers Pictures Inc.', 'id': 9233}]",5/19/58,65.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Attack of the 50 Foot Woman,"[{'id': 9748, 'name': 'revenge'}, {'id': 9951, 'name': 'alien'}, {'id': 11034, 'name': 'b movie'}, {'id': 11513, 'name': 'cheating husband'}, {'id': 14819, 'name': 'violence'}, {'id': 15184, 'name': 'woman'}, {'id': 189099, 'name': 'giant'}, {'id': 208199, 'name': 'chrysler imperial'}]","[{'cast_id': 2, 'character': 'Nancy Fowler Archer', 'credit_id': '52fe47949251416c7509e999', 'gender': 1, 'id': 104412, 'name': 'Allison Hayes', 'order': 0, 'profile_path': '/6VoMLGGRH1ccl25cyaHJWyMapD0.jpg'}, {'cast_id': 3, 'character': 'Harry Archer', 'credit_id': '52fe47949251416c7509e99d', 'gender': 0, 'id': 108299, 'name': 'William Hudson', 'order': 1, 'profile_path': '/yJDm8q5pzge2HfDeN9..."
2,3003,0,"[{'id': 35, 'name': 'Comedy'}, {'id': 10749, 'name': 'Romance'}]",Addicted to Love,8.085194,"[{'name': 'Warner Bros.', 'id': 6194}, {'name': 'Outlaw Productions (I)', 'id': 19507}, {'name': 'Miramax', 'id': 53009}]",5/23/97,100.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Addicted to Love,"[{'id': 931, 'name': 'jealousy'}, {'id': 9673, 'name': 'love'}, {'id': 9748, 'name': 'revenge'}, {'id': 14602, 'name': 'break-up'}]","[{'cast_id': 11, 'character': 'Maggie', 'credit_id': '52fe4330c3a36847f804139b', 'gender': 1, 'id': 5344, 'name': 'Meg Ryan', 'order': 0, 'profile_path': '/iv33eEcSakPCkO2MiR4bIZpjgyg.jpg'}, {'cast_id': 12, 'character': 'Sam', 'credit_id': '52fe4330c3a36847f804139f', 'gender': 2, 'id': 4756, 'name': 'Matthew Broderick', 'order': 1, 'profile_path': '/j9ETatVKFxYR5Ijk8l5tzKO4HPn.jpg'}, {'cast_id..."
3,3004,6800000,"[{'id': 18, 'name': 'Drama'}, {'id': 10752, 'name': 'War'}, {'id': 9648, 'name': 'Mystery'}]",Incendies,8.596012,"[{'name': 'TS Productions', 'id': 313}, {'name': 'Micro scope', 'id': 7272}, {'name': 'Phi Group', 'id': 7273}]",9/4/10,130.0,"[{'iso_639_1': 'fr', 'name': 'Français'}, {'iso_639_1': 'ar', 'name': 'العربية'}, {'iso_639_1': 'en', 'name': 'English'}]",Incendies,"[{'id': 378, 'name': 'prison'}, {'id': 539, 'name': 'middle east'}, {'id': 570, 'name': 'rape'}, {'id': 789, 'name': 'muslim'}, {'id': 1550, 'name': 'militia'}, {'id': 2297, 'name': 'interpreter'}, {'id': 5153, 'name': 'son'}, {'id': 5950, 'name': 'christian'}, {'id': 6783, 'name': 'orphanage'}, {'id': 8181, 'name': 'swimming pool'}, {'id': 14546, 'name': 'massacre'}, {'id': 14547, 'name': 'ch...","[{'cast_id': 6, 'character': 'Nawal', 'credit_id': '52fe470ac3a36847f812058b', 'gender': 1, 'id': 77498, 'name': 'Lubna Azabal', 'order': 0, 'profile_path': '/lGvB2xP7sotwSslSTovL5nxnzBC.jpg'}, {'cast_id': 7, 'character': 'Jeanne Marwan', 'credit_id': '52fe470ac3a36847f812058f', 'gender': 1, 'id': 84573, 'name': 'M√©lissa D√©sormeaux-Poulin', 'order': 1, 'profile_path': '/aBiUPDJwHwdcGPfEpi8kl..."
4,3005,2000000,"[{'id': 36, 'name': 'History'}, {'id': 99, 'name': 'Documentary'}]",Inside Deep Throat,3.217680,NaN,2/11/05,92.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Inside Deep Throat,"[{'id': 279, 'name': 'usa'}, {'id': 1228, 'name': '1970s'}, {'id': 5436, 'name': 'sexual revolution'}, {'id': 12420, 'name': 'unsimulated sex'}]","[{'cast_id': 1, 'character': 'Narrator (voice)', 'credit_id': '52fe44ce9251416c75041931', 'gender': 2, 'id': 2778, 'name': 'Dennis Hopper', 'order': 0, 'profile_path': '/56nj2DfMVU3F9qUagZWMePLbrKF.jpg'}, {'cast_id': 2, 'character': 'Himself', 'credit_id': '52fe44ce9251416c75041935', 'gender': 2, 'id': 71766, 'name': 'Peter Bart', 'order': 1, 'profile_path': '/iSDH6UtPjjKjJwzJWkbXhlljxAr.jpg'}..."

In [38]:
complete_movies_df_clean = pd.concat([movies_df_clean, movies_df_2_clean])
complete_movies_df_clean.head(10)

,id,budget,genres,original_title,popularity,production_companies,release_date,runtime,spoken_languages,title,Keywords,cast,revenue
0,1,14000000,"[{'id': 35, 'name': 'Comedy'}]",Hot Tub Time Machine 2,6.575393,"[{'name': 'Paramount Pictures', 'id': 4}, {'name': 'United Artists', 'id': 60}, {'name': 'Metro-Goldwyn-Mayer (MGM)', 'id': 8411}]",2/20/15,93.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Hot Tub Time Machine 2,"[{'id': 4379, 'name': 'time travel'}, {'id': 9663, 'name': 'sequel'}, {'id': 11830, 'name': 'hot tub'}, {'id': 179431, 'name': 'duringcreditsstinger'}]","[{'cast_id': 4, 'character': 'Lou', 'credit_id': '52fe4ee7c3a36847f82afae7', 'gender': 2, 'id': 52997, 'name': 'Rob Corddry', 'order': 0, 'profile_path': '/k2zJL0V1nEZuFT08xUdOd3ucfXz.jpg'}, {'cast_id': 5, 'character': 'Nick', 'credit_id': '52fe4ee7c3a36847f82afaeb', 'gender': 2, 'id': 64342, 'name': 'Craig Robinson', 'order': 1, 'profile_path': '/tVaRMkJXOEVhYxtnnFuhqW0Rjzz.jpg'}, {'cast_id':...",12314651.0
1,2,40000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'name': 'Drama'}, {'id': 10751, 'name': 'Family'}, {'id': 10749, 'name': 'Romance'}]",The Princess Diaries 2: Royal Engagement,8.248895,"[{'name': 'Walt Disney Pictures', 'id': 2}]",8/6/04,113.0,"[{'iso_639_1': 'en', 'name': 'English'}]",The Princess Diaries 2: Royal Engagement,"[{'id': 2505, 'name': 'coronation'}, {'id': 4263, 'name': 'duty'}, {'id': 6038, 'name': 'marriage'}, {'id': 13072, 'name': 'falling in love'}]","[{'cast_id': 1, 'character': 'Mia Thermopolis', 'credit_id': '52fe43fe9251416c7502561f', 'gender': 1, 'id': 1813, 'name': 'Anne Hathaway', 'order': 0, 'profile_path': '/jUMOKwSUBnTcMeN1HfhutiY49Ad.jpg'}, {'cast_id': 2, 'character': 'Queen Clarisse Renaldi', 'credit_id': '52fe43fe9251416c75025623', 'gender': 1, 'id': 5823, 'name': 'Julie Andrews', 'order': 1, 'profile_path': '/6t61jkmfSA6nbYRCK...",95149435.0
2,3,3300000,"[{'id': 18, 'name': 'Drama'}]",Whiplash,64.299990,"[{'name': 'Bold Films', 'id': 2266}, {'name': 'Blumhouse Productions', 'id': 3172}, {'name': 'Right of Way Films', 'id': 32157}]",10/10/14,105.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Whiplash,"[{'id': 1416, 'name': 'jazz'}, {'id': 1523, 'name': 'obsession'}, {'id': 1640, 'name': 'conservatory'}, {'id': 2176, 'name': 'music teacher'}, {'id': 14512, 'name': 'new york city'}, {'id': 14819, 'name': 'violence'}, {'id': 33896, 'name': 'montage'}, {'id': 156823, 'name': 'drummer'}, {'id': 170418, 'name': 'public humiliation'}, {'id': 176095, 'name': 'jazz band'}, {'id': 206298, 'name': 'yo...","[{'cast_id': 5, 'character': 'Andrew Neimann', 'credit_id': '52fe4ef7c3a36847f82b3fc3', 'gender': 2, 'id': 996701, 'name': 'Miles Teller', 'order': 0, 'profile_path': '/o2wfvYAvspsKqYVt4ORR8VWjB7H.jpg'}, {'cast_id': 6, 'character': 'Terence Fletcher', 'credit_id': '52fe4ef7c3a36847f82b3fc7', 'gender': 2, 'id': 18999, 'name': 'J.K. Simmons', 'order': 1, 'profile_path': '/jPoNW5fugs5h8AbcE7H5OBm...",13092000.0
3,4,1200000,"[{'id': 53, 'name': 'Thriller'}, {'id': 18, 'name': 'Drama'}]",Kahaani,3.174936,NaN,3/9/12,122.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso_639_1': 'hi', 'name': 'हिन्दी'}]",Kahaani,"[{'id': 10092, 'name': 'mystery'}, {'id': 10540, 'name': 'bollywood'}, {'id': 11734, 'name': 'police corruption'}, {'id': 14536, 'name': 'crime'}, {'id': 14636, 'name': 'india'}, {'id': 208364, 'name': 'missing husband'}, {'id': 220935, 'name': 'nerve gas'}]","[{'cast_id': 1, 'character': 'Vidya Bagchi', 'credit_id': '52fe48779251416c9108d6d9', 'gender': 1, 'id': 35068, 'name': 'Vidya Balan', 'order': 0, 'profile_path': '/anMmmqKY11jcm0UnSSakfNOSCyB.jpg'}, {'cast_id': 5, 'character': '', 'credit_id': '57722abec3a368245b004519', 'gender': 2, 'id': 85047, 'name': 'Nawazuddin Siddiqui', 'order': 1, 'profile_path': '/2Kv2ENAs1ETAFTQ6mC1jbDzEzIN.jpg'}, {...",16000000.0
4,5,0,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'name': 'Thriller'}]",마린보이,1.148070,NaN,2/5/09,118.0,"[{'iso_639_1': 'ko', 'name': '한국어/조선말'}]",Marine Boy,NaN,"[{'cast_id': 3, 'character': 'Chun-soo', 'credit_id': '52fe464b9251416c75073b47', 'gender': 2, 'id': 84751, 'name': 'Kim Kang-woo', 'order': 0, 'profile_path': '/lJvcgUx1qEnNfGcCtbmp3EC5vCG.jpg'}, {'cast_id': 4, 'character': 'Company president Kang', 'credit_id': '52fe464b9251416c75073b4b', 'gender': 2, 'id': 64453, 'name': 'Jo Jae-hyeon', 'order': 1, 'profile_path': '/2QVUP8t3zmKcwlm7IBOzPVik...",3923970.0
5,6,8000000,"[{'id': 16, 'name': 'Animation'}, {'id': 12, 'name': 'Adventure'}, {'id': 10751, 'name': 'Family'}]",Pinocchio and the Emperor of the Night,0.743274,NaN,8/6/87,83.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Pinocchio and the Emperor of the Night,NaN,"[{'cast_id': 6, 'character': 'Pinocchio (voice)', 'credit_id': '52fe46f49251416c9106558f', 'gender': 2, 'id': 35091, 'name': 'Scott Grimes', 'order': 0, 'profile_path': '/tm8uz3DbD0hlXRciYgCuaHrXepl.jpg'}, {'cast_id': 7, 'character': 'Geppetto (voice)', 'credit_id': '52fe46f49251416c91065593', 'gender': 2, 'id': 41217, 'name': 'Tom Bosley', 'order': 1, 'profile_path': '/9S95lnM10Qa3PGY86o7dvSF...",3261638.0
6,7,14000000,"[{'id': 27, 'name': 'Horror'}, {'id': 53, 'name': 'Thriller'}]",The Possession,7.286477,"[{'name': 'Ghost House Pictures', 'id': 768}, {'name': 'North Box Productions', 'id': 22637}]",8/30/12,92.0,"[{'iso_639_1': 'en', 'name': 'English'}]",The Possession,NaN,"[{'cast_id': 23, 'character': 'Clyde', 'credit_id': '52fe4981c3a368484e12ee17', 'gender': 2, 'id': 47296, 'name': 'Jeffrey Dean Morgan', 'order': 0, 'profile_path': '/6ors2HGy8UdXm8kBx6on0HwRHB5.jpg'}, {'cast_id': 31, 'character': 'Em', 'credit_id': '52fe4981c3a368484e12ee39', 'gender': 0, 'id': 94482, 'name': 'Natasha Calis', 'order': 1, 'profile_path': '/i6txLt6FyZW7G7thV5AmTeHtWrC.jpg'}, {'...",85446075.0
7,8,0,"[{'id': 99, 'name': 'Documentary'}]",Control Room,1.949044,NaN,1/15/04,84.0,"[{'iso_639_1': 'ar', 'name': 'العربية'}, {'iso_639_1': 'en', 'name': 'English'}]",Control Room,"[{'id': 917, 'name': 'journalism'}, {'id': 1638, 'name': 'translation'}, {'id': 2136, 'name': 'television'}, {'id': 2954, 'name': 'manipulation of the media'}, {'id': 5939, 'name': 'iraq'}, {'id': 12193, 'name': 'reporter'}, {'id': 187056, 'name': 'woman director'}]","[{'cast_id': 2, 'character': 'Himself', 'credit_id': '52fe47a69251416c750a0db3', 'gender': 0, 'id': 556951, 'name': 'Samir Khader', 'order': 0, 'profile_path': '/aE8pJJpgngwrOGXNoSEzneqGAXS.jpg'}, {'cast_id': 3, 'character': 'Himself (as Lt. Josh Rushing)', 'credit_id': '52fe47a69251416c750a0db7', 'gender': 0, 'id': 556952, 'name': 'Josh Rushing', 'order': 1, 'profile_path': '/2ZVuvL7k3q9I3nGp...",2586511.0
8,9,0,"[{'id': 28, 'name': 'Action'}, {'id': 35, 'name': 'Comedy'}, {'id': 10402, 'name': 'Music'}, {'id': 10751, 'name': 'Family'}, {'id': 12, 'name': 'Adventure'}]",Muppet Treasure Island,6.902423,"[{'name': 'Walt Disney Pictures', 'id': 2}, {'name': 'Jim Henson Productions', 'id': 2504}, {'name': 'Jim Henson Company, The', 'id': 6254}]",2/16/96,100.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Muppet Treasure Island,"[{'id': 2041, 'name': 'island'}, {'id': 4418, 'name': 'pirate gang'}, {'id': 6300, 'name': 'puppet'}, {'id': 6956, 'name': 'treasure hunt'}]","[{'cast_id': 1, 'character': 'Long John Silver', 'credit_id': '52fe43c89251416c7501dea1', 'gender': 2, 'id': 13472, 'name': 'Tim Curry', 'order': 0, 'profile_path': '/eo8AHZqSKuPconj1ueXHHBS37pM.jpg'}, {'cast_id': 2, 'character': 'Jim Hawkins', 'credit_id': '52fe43c89251416c7501dea5', 'gender': 2, 'id': 19996, 'name': 'Kevin Bishop', 'order': 1, 'profile_path': '/uiRRSgBK05xrjzGecbp2Oz8SYN8.jp...",34327391.0
9,10,6000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 10402, 'name': 'Music'}]",A Mighty Wind,4.672036,"[{'name': 'Castle Rock Entertainment', 'id': 97}]",4/16/03,91.0,"[{'iso_639_1': 'en', 'name': 'English'}]",A Mighty Wind,"[{'id': 11800, 'name': 'mockumentary'}, {'id': 33534, 'name': 'folk singer'}]","[{'cast_id': 24, 'character': 'Jonathan Steinbloom', 'credit_id': '54165a5dc3a3684d06003f19', 'gender': 2, 'id': 12438, 'name': 'Bob Balaban', 'order': 0, 'profile_path': '/3g7IKz8ycv0opDxmpoBxsQkUslU.jpg'}, {'cast_id': 5, 'character': 'Alan Barrows', 'credit_id': '52fe45609251416c75054595', 'gender': 2, 'id': 13524, 'name': 'Christopher Guest', 'order': 1, 'profile_path': '/fhEQq0q2aR2sh4HU82...",18750246.0

In [39]:
complete_movies_df_clean.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7398 entries, 0 to 4397
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    7398 non-null   int64
 1   budget                7398 non-null   int64
 2   genres                7375 non-null   object
 3   original_title        7398 non-null   object
 4   popularity            7398 non-null   float64
 5   production_companies  6984 non-null   object
 6   release_date          7397 non-null   object
 7   runtime               7392 non-null   float64
 8   spoken_languages      7336 non-null   object
 9   title                 7395 non-null   object
 10  Keywords              6729 non-null   object
 11  cast                  7372 non-null   object
 12  revenue               3000 non-null   float64
dtypes: float64(3), int64(2), object(8)
memory usage: 809.2+ KB

In [45]:
complete_movies_rename = complete_movies_df_clean.rename(columns={"cast": "actors"})
complete_movies_rename

,id,budget,genres,original_title,popularity,production_companies,release_date,runtime,spoken_languages,title,Keywords,actors,revenue
0,1,14000000,"[{'id': 35, 'name': 'Comedy'}]",Hot Tub Time Machine 2,6.575393,"[{'name': 'Paramount Pictures', 'id': 4}, {'name': 'United Artists', 'id': 60}, {'name': 'Metro-Goldwyn-Mayer (MGM)', 'id': 8411}]",2/20/15,93.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Hot Tub Time Machine 2,"[{'id': 4379, 'name': 'time travel'}, {'id': 9663, 'name': 'sequel'}, {'id': 11830, 'name': 'hot tub'}, {'id': 179431, 'name': 'duringcreditsstinger'}]","[{'cast_id': 4, 'character': 'Lou', 'credit_id': '52fe4ee7c3a36847f82afae7', 'gender': 2, 'id': 52997, 'name': 'Rob Corddry', 'order': 0, 'profile_path': '/k2zJL0V1nEZuFT08xUdOd3ucfXz.jpg'}, {'cast_id': 5, 'character': 'Nick', 'credit_id': '52fe4ee7c3a36847f82afaeb', 'gender': 2, 'id': 64342, 'name': 'Craig Robinson', 'order': 1, 'profile_path': '/tVaRMkJXOEVhYxtnnFuhqW0Rjzz.jpg'}, {'cast_id':...",12314651.0
1,2,40000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'name': 'Drama'}, {'id': 10751, 'name': 'Family'}, {'id': 10749, 'name': 'Romance'}]",The Princess Diaries 2: Royal Engagement,8.248895,"[{'name': 'Walt Disney Pictures', 'id': 2}]",8/6/04,113.0,"[{'iso_639_1': 'en', 'name': 'English'}]",The Princess Diaries 2: Royal Engagement,"[{'id': 2505, 'name': 'coronation'}, {'id': 4263, 'name': 'duty'}, {'id': 6038, 'name': 'marriage'}, {'id': 13072, 'name': 'falling in love'}]","[{'cast_id': 1, 'character': 'Mia Thermopolis', 'credit_id': '52fe43fe9251416c7502561f', 'gender': 1, 'id': 1813, 'name': 'Anne Hathaway', 'order': 0, 'profile_path': '/jUMOKwSUBnTcMeN1HfhutiY49Ad.jpg'}, {'cast_id': 2, 'character': 'Queen Clarisse Renaldi', 'credit_id': '52fe43fe9251416c75025623', 'gender': 1, 'id': 5823, 'name': 'Julie Andrews', 'order': 1, 'profile_path': '/6t61jkmfSA6nbYRCK...",95149435.0
2,3,3300000,"[{'id': 18, 'name': 'Drama'}]",Whiplash,64.299990,"[{'name': 'Bold Films', 'id': 2266}, {'name': 'Blumhouse Productions', 'id': 3172}, {'name': 'Right of Way Films', 'id': 32157}]",10/10/14,105.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Whiplash,"[{'id': 1416, 'name': 'jazz'}, {'id': 1523, 'name': 'obsession'}, {'id': 1640, 'name': 'conservatory'}, {'id': 2176, 'name': 'music teacher'}, {'id': 14512, 'name': 'new york city'}, {'id': 14819, 'name': 'violence'}, {'id': 33896, 'name': 'montage'}, {'id': 156823, 'name': 'drummer'}, {'id': 170418, 'name': 'public humiliation'}, {'id': 176095, 'name': 'jazz band'}, {'id': 206298, 'name': 'yo...","[{'cast_id': 5, 'character': 'Andrew Neimann', 'credit_id': '52fe4ef7c3a36847f82b3fc3', 'gender': 2, 'id': 996701, 'name': 'Miles Teller', 'order': 0, 'profile_path': '/o2wfvYAvspsKqYVt4ORR8VWjB7H.jpg'}, {'cast_id': 6, 'character': 'Terence Fletcher', 'credit_id': '52fe4ef7c3a36847f82b3fc7', 'gender': 2, 'id': 18999, 'name': 'J.K. Simmons', 'order': 1, 'profile_path': '/jPoNW5fugs5h8AbcE7H5OBm...",13092000.0
3,4,1200000,"[{'id': 53, 'name': 'Thriller'}, {'id': 18, 'name': 'Drama'}]",Kahaani,3.174936,NaN,3/9/12,122.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso_639_1': 'hi', 'name': 'हिन्दी'}]",Kahaani,"[{'id': 10092, 'name': 'mystery'}, {'id': 10540, 'name': 'bollywood'}, {'id': 11734, 'name': 'police corruption'}, {'id': 14536, 'name': 'crime'}, {'id': 14636, 'name': 'india'}, {'id': 208364, 'name': 'missing husband'}, {'id': 220935, 'name': 'nerve gas'}]","[{'cast_id': 1, 'character': 'Vidya Bagchi', 'credit_id': '52fe48779251416c9108d6d9', 'gender': 1, 'id': 35068, 'name': 'Vidya Balan', 'order': 0, 'profile_path': '/anMmmqKY11jcm0UnSSakfNOSCyB.jpg'}, {'cast_id': 5, 'character': '', 'credit_id': '57722abec3a368245b004519', 'gender': 2, 'id': 85047, 'name': 'Nawazuddin Siddiqui', 'order': 1, 'profile_path': '/2Kv2ENAs1ETAFTQ6mC1jbDzEzIN.jpg'}, {...",16000000.0
4,5,0,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'name': 'Thriller'}]",마린보이,1.148070,NaN,2/5/09,118.0,"[{'iso_639_1': 'ko', 'name': '한국어/조선말'}]",Marine Boy,NaN,"[{'cast_id': 3, 'character': 'Chun-soo', 'credit_id': '52fe464b9251416c75073b47', 'gender': 2, 'id': 84751, 'name': 'Kim Kang-woo', 'order': 0, 'profile_path': '/lJvcgUx1qEnNfGcCtbmp3EC5vCG.jpg'}, {'cast_id': 4, 'character': 'Company president Kang', 'credit_id': '52fe464b9251416c75073b4b', 'gender': 2, 'id': 64453, 'name': 'Jo Jae-hyeon', 'order': 1, 'profile_path': '/2QVUP8t3zmKcwlm7IBOzPVik...",3923970.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4393,7394,42000000,"[{'id': 53, 'name': 'Thriller'}]",Original Sin,9.970359,"[{'name': 'Intermedia Films', 'id': 763}, {'name': 'DiNovi Pictures', 'id': 813}, {'name': 'Epsilon Motion Pictures', 'id': 1171}, {'name': 'Metro-Goldwyn-Mayer (MGM)', 'id': 8411}, {'name': 'Via Rosa Productions', 'id': 10103}, {'name': 'Hyde Park Entertainment', 'id': 13816}, {'name': 'UGC DA International', 'id': 76083}]",8/3/01,118.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso_639_1': 'de', 'name': 'Deutsch'}, {'iso_639_1': 'ja', 'name': '日本語'}, {'iso_639_1': 'la', 'name': 'Latin'}, {'iso_639_1': 'es', 'name': 'Español'}]",Original Sin,"[{'id': 515, 'name': 'women'}, {'id': 572, 'name': 'sex'}, {'id': 701, 'name': 'cuba'}, {'id': 1664, 'name': 'eroticism'}, {'id': 1808, 'name': 'lover (female)'}, {'id': 2983, 'name': 'passion'}, {'id': 6180, 'name': 'coffee grower'}, {'id': 7412, 'name': 'sin'}, {'id': 197602, 'name': 'denunciation'}]","[{'cast_id': 17, 'character': 'Julia Russell/Bonnie Castle', 'credit_id': '52fe4330c3a36847f8041327', 'gender': 1, 'id': 11701, 'name': 'Angelina Jolie', 'order': 0, 'profile_path': '/nsxtg9MQG01hvud1vVEW9vvfukK.jpg'}, {'cast_id': 11, 'character': 'Luis Antonio Vargas', 'credit_id': '52fe4330c3a36847f804130f', 'gender': 2, 'id': 3131, 'name': 'Antonio Banderas', 'order': 1, 'profile_path': '/8...",NaN
4394,7395,19000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'name': 'Adventure'}, {'id': 35, 'name': 'Comedy'}, {'id': 53, 'name': 'Thriller'}]",Without a Paddle,6.046516,"[{'name': 'Paramount Pictures', 'id': 4}, {'name': 'De Line Pictures', 'id': 2609}]",8/20/04,95.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Without a Paddle,"[{'id': 4959, 'name': 'death of a friend'}, {'id': 6956, 'name': 'treasure hunt'}]","[{'cast_id': 40, 'character': 'Dan Mott', 'credit_id': '52fe43b29251416c7501a96b', 'gender': 2, 'id': 13922, 'name': 'Seth Green', 'order': 0, 'profile_path': '/7ksgEtZZIhSkJmt7zMyVDOQfdxu.jpg'}, {'cast_id': 27, 'character': 'Jerry Conlaine', 'credit_id': '52fe43b29251416c7501a937', 'gender': 2, 'id': 26457, 'name': 'Matthew Lillard', 'order': 1, 'profile_path': '/gJsQkX20g0ABquHqVpBJzMXR2JF.j...",NaN
4395,7396,16000000,"[{'id': 18, 'name': 'Drama'}]",The Verdict,9.596883,"[{'name': 'Twentieth Century Fox Film Corporation', 'id': 306}]",12/8/82,129.0,"[{'iso_639_1': 'en', 'name': 'English'}]",The Verdict,"[{'id': 1680, 'name': 'boston'}, {'id': 6148, 'name': 'court'}, {'id': 10498, 'name': 'malpractice'}, {'id': 33457, 'name': 'alcoholic'}, {'id': 33519, 'name': 'courtroom'}, {'id': 155873, 'name': 'defense attorney'}]","[{'cast_id': 1, 'character': 'Frank Galvin', 'credit_id': '52fe448bc3a368484e028c0b', 'gender': 2, 'id': 3636, 'name': 'Paul Newman', 'order': 0, 'profile_path': '/my0Blo9IBy1WZ0QKbuxUzS0QwV5.jpg'}, {'cast_id': 2, 'character': 'Laura Fischer', 'credit_id': '52fe448bc3a368484e028c0f', 'gender': 1, 'id': 44079, 'name': 'Charlotte Rampling', 'order': 1, 'profile_path': '/iuggCphmBfNoUFaUWfpJCTxX4...",NaN
4396,7397,2000000,"[{'id': 27, 'name': 'Horror'}, {'id': 53, 'name': 'Thriller'}]",It Follows,20.359336,"[{'name': 'Northern Lights Films', 'id': 8714}, {'name': 'Animal Kingdom', 'id': 26995}, {'name': 'Two Flints', 'id': 52739}]",2/4/15,100.0,"[{'iso_639_1': 'en', 'name': 'English'}]",It Follows,"[{'id': 3713, 'name': 'chase'}, {'id': 6152, 'name': 'supernatural'}, {'id': 9713, 'name': 'friends'}, {'id': 10629, 'name': 'vision'}, {'id': 10873, 'name': 'school'}, {'id': 206298, 'name': 'young adult'}, {'id': 209141, 'name': 'followed'}]","[{'cast_id': 1, 'character': 'Jay Height', 'credit_id': '537770fd0e0a2614190021d7', 'gender': 1, 'id': 1094091, 'name': 'Maika Monroe', 'order': 0, 'profile_path': '/lid7Ma3Ja9H1up3IjNGDB4fOrJM.jpg'}, {'cast_id': 2, 'character': 'Paul', 'credit_id': '537771140e0a2614250022bc', 'gender': 2, 'id': 132712, 'name': 'Keir Gilchrist', 'order': 1, 'profile_path': '/vFrziqS1PDoHYFs2Vn9ro3577Ry.jpg'}, ...",NaN
4397,7398,64000,"[{'id': 18, 'name': 'Drama'}]",Vivre sa vie: film en douze tableaux,11.305910,"[{'name': 'Pathé Consortium Cinéma', 'id': 220}, {'name': 'Les Films de la Pléiade', 'id': 745}, {'name': 'The Criterion Collection', 'id': 10932}]",9/20/62,85.0,"[{'iso_639_1': 'fr', 'name': 'Français'}]",Vivre Sa Vie,"[{'id': 90, 'name': 'paris'}, {'id': 490, 'name': 'philosophy'}, {'id': 549, 'name': 'prostitute'}, {'id': 1667, 'name': 'pimp'}, {'id': 11322, 'name': 'female protagonist'}, {'id': 13059, 'name': 'prostitution'}, {'id': 18091, 'name': 'free will'}, {'id': 157217, 'name': 'woman smoking'}, {'id': 170710, 'name': 'pinball machine'}, {'id': 177370, 'name': 'rule of law'}]","[{'cast_id': 8, 'character': 'Nana Kleinfrankenheim', 'credit_id': '52fe4306c3a36847f80349a9', 'gender': 1, 'id': 18197, 'name': 'Anna Karina', 'order': 0, 'profile_path': '/dEx50cajhgno1eK9A7bBBMmgA8g.jpg'}, {'cast_id': 9, 'character': 'Raoul', 'credit_id': '52fe4306c3a36847f80349ad', 'gender': 0, 'id': 18198, 'name': 'Sady Rebbot', 'order': 1, 'profile_path': '/hVs6YjJfw1HIQCGMN5gnubHBVx8.jp...",NaN

In [46]:
nan_counts = complete_movies_df_clean.isna().sum()
nan_counts

id                         0
budget                     0
genres                    23
original_title             0
popularity                 0
production_companies     414
release_date               1
runtime                    6
spoken_languages          62
title                      3
Keywords                 669
cast                      26
revenue                 4398
dtype: int64

In [47]:
complete_movies_df_clean_all = complete_movies_rename.dropna()
complete_movies_df_clean_all

,id,budget,genres,original_title,popularity,production_companies,release_date,runtime,spoken_languages,title,Keywords,actors,revenue
0,1,14000000,"[{'id': 35, 'name': 'Comedy'}]",Hot Tub Time Machine 2,6.575393,"[{'name': 'Paramount Pictures', 'id': 4}, {'name': 'United Artists', 'id': 60}, {'name': 'Metro-Goldwyn-Mayer (MGM)', 'id': 8411}]",2/20/15,93.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Hot Tub Time Machine 2,"[{'id': 4379, 'name': 'time travel'}, {'id': 9663, 'name': 'sequel'}, {'id': 11830, 'name': 'hot tub'}, {'id': 179431, 'name': 'duringcreditsstinger'}]","[{'cast_id': 4, 'character': 'Lou', 'credit_id': '52fe4ee7c3a36847f82afae7', 'gender': 2, 'id': 52997, 'name': 'Rob Corddry', 'order': 0, 'profile_path': '/k2zJL0V1nEZuFT08xUdOd3ucfXz.jpg'}, {'cast_id': 5, 'character': 'Nick', 'credit_id': '52fe4ee7c3a36847f82afaeb', 'gender': 2, 'id': 64342, 'name': 'Craig Robinson', 'order': 1, 'profile_path': '/tVaRMkJXOEVhYxtnnFuhqW0Rjzz.jpg'}, {'cast_id':...",12314651.0
1,2,40000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'name': 'Drama'}, {'id': 10751, 'name': 'Family'}, {'id': 10749, 'name': 'Romance'}]",The Princess Diaries 2: Royal Engagement,8.248895,"[{'name': 'Walt Disney Pictures', 'id': 2}]",8/6/04,113.0,"[{'iso_639_1': 'en', 'name': 'English'}]",The Princess Diaries 2: Royal Engagement,"[{'id': 2505, 'name': 'coronation'}, {'id': 4263, 'name': 'duty'}, {'id': 6038, 'name': 'marriage'}, {'id': 13072, 'name': 'falling in love'}]","[{'cast_id': 1, 'character': 'Mia Thermopolis', 'credit_id': '52fe43fe9251416c7502561f', 'gender': 1, 'id': 1813, 'name': 'Anne Hathaway', 'order': 0, 'profile_path': '/jUMOKwSUBnTcMeN1HfhutiY49Ad.jpg'}, {'cast_id': 2, 'character': 'Queen Clarisse Renaldi', 'credit_id': '52fe43fe9251416c75025623', 'gender': 1, 'id': 5823, 'name': 'Julie Andrews', 'order': 1, 'profile_path': '/6t61jkmfSA6nbYRCK...",95149435.0
2,3,3300000,"[{'id': 18, 'name': 'Drama'}]",Whiplash,64.299990,"[{'name': 'Bold Films', 'id': 2266}, {'name': 'Blumhouse Productions', 'id': 3172}, {'name': 'Right of Way Films', 'id': 32157}]",10/10/14,105.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Whiplash,"[{'id': 1416, 'name': 'jazz'}, {'id': 1523, 'name': 'obsession'}, {'id': 1640, 'name': 'conservatory'}, {'id': 2176, 'name': 'music teacher'}, {'id': 14512, 'name': 'new york city'}, {'id': 14819, 'name': 'violence'}, {'id': 33896, 'name': 'montage'}, {'id': 156823, 'name': 'drummer'}, {'id': 170418, 'name': 'public humiliation'}, {'id': 176095, 'name': 'jazz band'}, {'id': 206298, 'name': 'yo...","[{'cast_id': 5, 'character': 'Andrew Neimann', 'credit_id': '52fe4ef7c3a36847f82b3fc3', 'gender': 2, 'id': 996701, 'name': 'Miles Teller', 'order': 0, 'profile_path': '/o2wfvYAvspsKqYVt4ORR8VWjB7H.jpg'}, {'cast_id': 6, 'character': 'Terence Fletcher', 'credit_id': '52fe4ef7c3a36847f82b3fc7', 'gender': 2, 'id': 18999, 'name': 'J.K. Simmons', 'order': 1, 'profile_path': '/jPoNW5fugs5h8AbcE7H5OBm...",13092000.0
8,9,0,"[{'id': 28, 'name': 'Action'}, {'id': 35, 'name': 'Comedy'}, {'id': 10402, 'name': 'Music'}, {'id': 10751, 'name': 'Family'}, {'id': 12, 'name': 'Adventure'}]",Muppet Treasure Island,6.902423,"[{'name': 'Walt Disney Pictures', 'id': 2}, {'name': 'Jim Henson Productions', 'id': 2504}, {'name': 'Jim Henson Company, The', 'id': 6254}]",2/16/96,100.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Muppet Treasure Island,"[{'id': 2041, 'name': 'island'}, {'id': 4418, 'name': 'pirate gang'}, {'id': 6300, 'name': 'puppet'}, {'id': 6956, 'name': 'treasure hunt'}]","[{'cast_id': 1, 'character': 'Long John Silver', 'credit_id': '52fe43c89251416c7501dea1', 'gender': 2, 'id': 13472, 'name': 'Tim Curry', 'order': 0, 'profile_path': '/eo8AHZqSKuPconj1ueXHHBS37pM.jpg'}, {'cast_id': 2, 'character': 'Jim Hawkins', 'credit_id': '52fe43c89251416c7501dea5', 'gender': 2, 'id': 19996, 'name': 'Kevin Bishop', 'order': 1, 'profile_path': '/uiRRSgBK05xrjzGecbp2Oz8SYN8.jp...",34327391.0
9,10,6000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 10402, 'name': 'Music'}]",A Mighty Wind,4.672036,"[{'name': 'Castle Rock Entertainment', 'id': 97}]",4/16/03,91.0,"[{'iso_639_1': 'en', 'name': 'English'}]",A Mighty Wind,"[{'id': 11800, 'name': 'mockumentary'}, {'id': 33534, 'name': 'folk singer'}]","[{'cast_id': 24, 'character': 'Jonathan Steinbloom', 'credit_id': '54165a5dc3a3684d06003f19', 'gender': 2, 'id': 12438, 'name': 'Bob Balaban', 'order': 0, 'profile_path': '/3g7IKz8ycv0opDxmpoBxsQkUslU.jpg'}, {'cast_id': 5, 'character': 'Alan Barrows', 'credit_id': '52fe45609251416c75054595', 'gender': 2, 'id': 13524, 'name': 'Christopher Guest', 'order': 1, 'profile_path': '/fhEQq0q2aR2sh4HU82...",18750246.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,2996,0,"[{'id': 35, 'name': 'Comedy'}, {'id': 10749, 'name': 'Romance'}]",Chasers,9.853270,"[{'name': 'Warner Bros.', 'id': 6194}, {'name': 'Morgan Creek Productions', 'id': 10210}]",4/22/94,102.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Chasers,"[{'id': 378, 'name': 'prison'}, {'id': 572, 'name': 'sex'}, {'id': 772, 'name': 'handcuffs'}, {'id': 828, 'name': 'waitress'}, {'id': 1721, 'name': 'fight'}, {'id': 2407, 'name': 'fireworks'}, {'id': 2483, 'name': 'nudity'}, {'id': 3347, 'name': 'volcano'}, {'id': 3588, 'name': 'navy'}, {'id': 7312, 'name': 'road trip'}, {'id': 10594, 'name': 'money'}, {'id': 10685, 'name': 'escape'}, {'id': 1...","[{'cast_id': 2, 'character': 'Rock Reilly', 'credit_id': '52fe4494c3a368484e02ac77', 'gender': 2, 'id': 13022, 'name': 'Tom Berenger', 'order': 0, 'profile_path': '/gueEBgqv1sWFemMXyI4TJ2peuMA.jpg'}, {'cast_id': 9, 'character': 'Eddie Devane', 'credit_id': '52fe4494c3a368484e02ac9f', 'gender': 2, 'id': 18687, 'name': 'William McNamara', 'order': 1, 'profile_path': '/c19069KdW7VW4h8Q5Cq35j8sOMl...",1596687.0
2996,2997,0,"[{'id': 18, 'name': 'Drama'}, {'id': 10402, 'name': 'Music'}]",Vi är bäst!,3.727996,"[{'name': 'Memfis Film', 'id': 321}, {'name': 'Film i Väst', 'id': 17513}]",3/28/13,102.0,"[{'iso_639_1': 'sv', 'name': 'svenska'}]",We Are the Best!,"[{'id': 1192, 'name': 'sweden'}, {'id': 4470, 'name': 'punk'}, {'id': 9717, 'name': 'based on comic'}, {'id': 160396, 'name': 'all girl band'}, {'id': 164060, 'name': 'girl band'}, {'id': 197619, 'name': 'foreign'}]","[{'cast_id': 5, 'character': 'Bobo', 'credit_id': '52fe4c7f9251416c910f6c4d', 'gender': 0, 'id': 1171819, 'name': 'Mira Barkhammar', 'order': 0, 'profile_path': None}, {'cast_id': 6, 'character': 'Klara', 'credit_id': '52fe4c7f9251416c910f6c51', 'gender': 0, 'id': 1171820, 'name': 'Mira Grosin', 'order': 1, 'profile_path': None}, {'cast_id': 7, 'character': 'Hedvig', 'credit_id': '52fe4c7f9251...",180590.0
2997,2998,65000000,"[{'id': 80, 'name': 'Crime'}, {'id': 28, 'name': 'Action'}, {'id': 9648, 'name': 'Mystery'}, {'id': 53, 'name': 'Thriller'}]",The Long Kiss Goodnight,14.482345,"[{'name': 'New Line Cinema', 'id': 12}, {'name': 'Forge', 'id': 2980}, {'name': 'The Steve Tisch Company', 'id': 21920}]",10/11/96,120.0,"[{'iso_639_1': 'en', 'name': 'English'}]",The Long Kiss Goodnight,"[{'id': 441, 'name': 'assassination'}, {'id': 1453, 'name': 'amnesia'}, {'id': 1562, 'name': 'hostage'}, {'id': 3713, 'name': 'chase'}, {'id': 10123, 'name': 'dark comedy'}, {'id': 10508, 'name': 'teacher'}, {'id': 10685, 'name': 'escape'}, {'id': 14768, 'name': 'single mother'}, {'id': 41414, 'name': 'timebomb'}, {'id': 166625, 'name': 'candlelight vigil'}, {'id': 176802, 'name': 'rogue agent...","[{'cast_id': 10, 'character': 'Samantha Caine / Charly Baltimore', 'credit_id': '52fe443b9251416c7502d5ad', 'gender': 1, 'id': 16935, 'name': 'Geena Davis', 'order': 0, 'profile_path': '/6b8cRJOItz7yNpYuLCPkl5kv4m2.jpg'}, {'cast_id': 12, 'character': 'Mitch Henessey', 'credit_id': '52fe443b9251416c7502d5b1', 'gender': 2, 'id': 2231, 'name': 'Samuel L. Jackson', 'order': 1, 'profile_path': '/Av...",89456761.0
2998,2999,42000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 10749, 'name': 'Romance'}]",Along Came Polly,15.725542,"[{'name': 'Jersey Films', 'id': 216}, {'name': 'Loofah Productions', 'id': 53626}]",1/16/04,90.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Along Came Polly,"[{'id': 966, 'name': 'beach'}, {'id': 2676, 'name': 'honeymoon'}, {'id': 3582, 'name': 'bride'}, {'id': 3817, 'name': 'chance'}, {'id': 4999, 'name': 'risk'}, {'id': 6192, 'name': 'relation'}, {'id': 9398, 'name': 'long island'}, {'id': 9799, 'name': 'romantic comedy'}, {'id': 10267, 'name': 'comedy'}, {'id': 10503, 'name': 'scuba diving'}, {'id': 11510, 'name': 'unfaithfulness'}, {'id': 12670...","[{'cast_id': 8, 'character': 'Reuben Feffer', 'credit_id': '52fe4432c3a36847f808804d', 'gender': 2, 'id': 7399, 'name': 'Ben Stiller', 'order': 0, 'profile_path': '/o9M2PyoF7QDSMq1OwW0D892fIkV.jpg'}, {'cast_id': 9, 'character': 'Polly Prince', 'credit_id': '52fe4432c3a36847f8088051', 'gender': 1, 'id': 4491, 'name': 'Jennifer Aniston', 'order': 1, 'profile_path': '/4d4wvNyDuvN86DoneawbLOpr8gH....",171963386.0
2999,3000,35000000,"[{'id': 53, 'name': 'Thriller'}, {'id': 28, 'name': 'Action'}, {'id': 9648, 'name': 'Mystery'}]",Abduction,10.512109,"[{'name': 'Lions Gate Films', 'id': 35}, {'name': 'Vertigo Entertainment', 'id': 829}, {'name': 'Gotham Group', 'id': 3672}, {'name': 'Tailor Made', 'id': 24557}, {'name': 'Mango Farms', 'id': 24558}, {'name': 'Quick Six Entertainment', 'id': 24561}]",9/22/11,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Abduction,"[{'id': 591, 'name': 'cia'}, {'id': 822, 'name': 'airport'}, {'id': 1701, 'name': 'hero'}, {'id': 1721, 'name': 'fight'}, {'id': 1930, 'name': 'kidnapping'}, {'id': 3562, 'name': 'time bomb'}, {'id': 4613, 'name': 'training'}, {'id': 6435, 'name': 'webcam'}, {'id': 6614, 'name': 'website'}, {'id': 8508, 'name': 'party'}, {'id': 10562, 'name': 'on the run'}, {'id': 11612, 'name': 'hospital'}, {...","[{'cast_id': 2, 'character': 'Nathan Harper', 'credit_id': '52fe49a5c3a36847f81a5137', 'gender': 2, 'id': 84214, 'name': 'Taylor Lautner', 'order': 0, 'profile_path': '/xazf3pX3fbScXvi8WojuxsGOJX2.jpg'}, {'cast_id': 3, 'character': 'Karen Murphy', 'credit_id': '52fe49a5c3a36847f81a513b', 'gender': 1, 'id': 112561, 'name': 'Lily Collins', 'order': 1, 'profile_path': '/zembz1s3BExSTgOGQTbMtXhvfN...",82087155.0

In [48]:
complete_movies_df_clean_all.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2616 entries, 0 to 2999
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    2616 non-null   int64
 1   budget                2616 non-null   int64
 2   genres                2616 non-null   object
 3   original_title        2616 non-null   object
 4   popularity            2616 non-null   float64
 5   production_companies  2616 non-null   object
 6   release_date          2616 non-null   object
 7   runtime               2616 non-null   float64
 8   spoken_languages      2616 non-null   object
 9   title                 2616 non-null   object
 10  Keywords              2616 non-null   object
 11  actors                2616 non-null   object
 12  revenue               2616 non-null   float64
dtypes: float64(3), int64(2), object(8)
memory usage: 286.1+ KB

In [ ]:
complete_movies_df_clean.to_csv('clean_csvs/complete_movie_list.csv', index=False)